version: '3.6'

services:
  alpine-binary-c-hl-hobo:
    build: .
    image: alpine-binary-c-hl:latest
    hostname: 'hobo'
    environment:
      - HL_USER_USERNAME=hacker
      - HL_USER_PASSWORD=compass
    ports:
      - "80:80"
      - "1234:1234"
